import turtle
turtle.setup(750,750,0,0)
kame=turtle.Turtle()
kame.shape('classic')
kame.shapesize(2,2,1)
kame.forward(150)
kame.forward(500)
kame.backward(500)
kame.right(90)
kame.left(180)
kame.circle(150)
kame.undo()
kame.home()
kame.clear()
yoko=kame.getscreen().window_width()
tate=kame.getscreen().window_height()
print(yoko)
print(tate)
print(kame.position())
kame.goto(150,200)
print(kame.position())
print(kame.distance(0,0))
kame.penup()
kame.circle(150)
print(kame.isdown())
kame.pendown()


turtle.done()